CREATE TABLE IF NOT EXISTS `text` (
    `id`   INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `text`   TEXT NOT NULL,
    `created_at` DATETIME  NOT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
